### ISSUE TITLE
2.0 Compatibility Checklist

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/SubnauticaRandomiser#48]
The randomiser is vulnerable to changes in so many aspects of the game, it makes sense to collect them all in one place to keep on top of things. Below should be a definitive list of things that need verifying to make sure the randomiser works as intended.

- [x] Recipes (afaik updated to use BZ's variant of CraftData)
- [x] TechTypes and names
- [x] Blueprints
- [x] Unlock requirements for blueprints, particularly non-obvious ones like multipurpose room --> plasteel. Scan KnownTech for this one.
- [x] Databox locations and CoordinatedSpawn behaviour
- [x] Fragment names and spawn rates
- [x] Biome names and internal structure, especially distinction between walls/floor/grass/other sub-biomes
- [ ] Spawn slots for everything
- [x] Lifepod spawning
- [x] IL code targeted by the transpiler responsible for randomising duplicate fragment rewards

New content:
- [x] What new recipes need adding?
- [x] New fragments? The huge room and glass dome especially

**Comment by jet082** [comment]
I've managed to build this project, so I'm keeping an eye on this and will gladly test 2.0 changes as you make them.

**Comment by tinyhoot** [comment]
I appreciate it. There won't be any working builds for 2.0 so long as SMLHelper isn't updated, but I'm considering some under-the-hood changes for legacy builds before that. Some parts of the project are showing their age, and I'd like to replace the particularly hacky parts with some more elegant bits.

**Comment by jet082** [comment]
It seems they are retiring QModManager and the project needs to be moved to BepinEx. I'm not sure how dramatic this impacts the code.

**Comment by tinyhoot** [comment]
Yeah, already saw it on the discord. This shouldn't be too much of a change. The conversion from QMM to BepinEx is fairly minimal. The big dependency has always been SMLHelper, which is much, much harder to go without. But that issue should eventually get resolved as well.

**Comment by tinyhoot** [comment]
Thanks to the hard work of the people mainting SMLHelper, I've been able to update almost everything. The code that's up on the living-large branch now brings the mod up to speed. It includes none of the underlying changes I'd like to get done, but there's always time for that later.

From my testing, it seems largely stable. Fragments are my main concern, as always. I'm not sure if they actually spawn often enough; it _seems_ like the spawn rates are about the same as before the update, but the randomiser introduces a lot of variance there.
